name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y g++
    - name: Build
      run: g++ -o test tests/test.cpp tests/catch_amalgamated.cpp -fopenmp
    - name: Run tests
      run: ./tests
